### ISSUE TITLE
Adjust Y-axis on figures

### ISSUE THREAD

**Issue by prvmalik** [msevestre/CKD-Qualification#44]

**Comment by msevestre** [comment]
@prvmalik Can you explain what needs to be done here?

**Comment by prvmalik** [comment]
Visually the graphs would improve by limiting the y axis  range to near the Cmin*0.1 and Cmax*5, or something similar. 

Paul

**Comment by prvmalik** [comment]
Thanks busy tonight but can send tomorrow

**Comment by msevestre** [comment]
sounds good. I need to wait until I get feedback for #51 so this is good

**Comment by msevestre** [comment]
Let's create an issue in the https://github.com/Open-Systems-Pharmacology/Qualification-CKD repo for this

**Comment by msevestre** [comment]
see https://github.com/Open-Systems-Pharmacology/Qualification-CKD/issues/2
