### ISSUE TITLE
Renumber figure captions according to text

### ISSUE THREAD

**Issue by prvmalik** [msevestre/CKD-Qualification#51]

**Comment by prvmalik** [comment]
E.g. Figure 3.1.2, etc. in the beginning of the caption label

**Comment by msevestre** [comment]
@Yuri05 @pchelle

A quick question here.
The generated file looks like this
![image](https://user-images.githubusercontent.com/1041237/202603295-c6b4301f-f62a-4287-b09d-00f59341d30e.png)

Figure 1 seems to be added automatically to the plot caption. How can I make sure that this number follows the convention in the text?  (figure 1 is used somewhere else for instance. Here it should be figure 3.2.3)

**Comment by prvmalik** [comment]
Maybe I can rename all of them in the text. I didn't come up with this naming convention only adopted it.

**Comment by msevestre** [comment]
Let's wait until we here how this is supposed to be done :)

**Comment by Yuri05** [comment]
@msevestre Did you use the latest RE release ([2.0.191](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/releases/tag/v2.0.191))? 
The convention for the figure numbering is `<Major chapter number>-<table/figure count within the chapter>`
Compare e.g. this report: https://github.com/Yuri05/Alfentanil-Model/blob/review/Evaluation/report/report.md#32-diagnostics-plots

So e.g. if the structure of the document is:
- Chapter 2
  - **figure**
- Chapter 2.1
  - **figure** 
- Chapter 3
  - no figures
- Chapter 3.1
  - no figures
- Chapter 3.2
  - **figure**
  - **figure**
- Chapter 3.3
  - **figure**
  - **figure**

In the report the automated numbering will generate the captions as:
- Chapter 2
  - **Figure 2-1:** 
- Chapter 2.1
  - **Figure 2-2:**
- Chapter 3
  - no figures
- Chapter 3.1
  - no figures
- Chapter 3.2
  - **Figure 3-1:**
  - **Figure 3-2:**
- Chapter 3.3
  - **Figure 3-3:**
  - **Figure 3-4:**

**Comment by msevestre** [comment]
nope. used one verison that was working on my machine. Did not want to risk it
All right, I'll update

**Comment by msevestre** [comment]
@Yuri05 I am wondering about this. Can we make the number relative to the chapter where it's define, not the TOP chapter?
otherwise, adding one plot in Chapter 3.1 messes up the numbering in Chapter 3.3. Feels weird

**Comment by Yuri05** [comment]
That was what the users wished: https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/issues/786

**Comment by msevestre** [comment]
Oh no I am not asking to change it. I am just wondering why this is done like this because this does not make sense to me :) I am fighting with all my files right now because of one wrong number somewhere else. FEels like programming leak all over again lol
